spring.application.name=springbootdemo
server.port=8088
spring.datasource.url=jdbc:mysql://192.168.1.210:3306/springbootdemo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ??sql
spring.jpa.show-sql=true
# ???sql
spring.jpa.properties.hibernate.format_sql=true
# ??????????
spring.jpa.hibernate.ddl-auto=update